services:
  - type: web
    name: codeverse-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: codeverse-db
          property: connectionString
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: codeverse-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: codeverse-db
          property: password

databases:
  - name: codeverse-db
    plan: free
